# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the nuxt branch
on:
  push:
    branches: [ nuxt ]
  pull_request:
    branches: [ nuxt ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
      - run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: eonix-net/eonix-net.github.io
          publish_dir: ./dist
          user_name: eonix-net
          user_email: vitalys@serverhub.com
          publish_branch: master
